version: '3'
services:
    nginx:
      build:
        context: docker
        dockerfile: ./docker/nginx/Dockerfile
      volumes:
        - .:/var/www/symfony/
      ports:
        - 80:80
      networks:
        - symfony
      depends_on:
        - php
    php:
      build:
        context: docker
        dockerfile: ./docker/php/Dockerfile
      volumes:
        - .:/var/www/symfony/
      networks:
        - symfony
networks:
  symfony:
